### ISSUE TITLE
Write area-of-gridcell component

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#153]
For #149, we need to know the area of each pixel.  This area calculation should be designed in a generic way to accommodate multiple types of grids: regular lat-lon, curvilinear (e.g., WRF), and possibly even irregular (though irregular would necessitate using a different type of connected component search).  Given the need for generality, and given that gridcell areas will be a useful component for other TECA algorithms, I would recommend that we separate out this area-of-gridcell code into its own algorithm.

One consideration is that this is a static quantity that should only need to be calculated once in the TECA run.  @burlen: does this make sense to you to have this be its own TECA algorithm?

See #146.

**Comment by burlen** [comment]
huh. I've been thinking about this as "area of connected component" rather than "area of grid cell". In the former coordinate arrays are passed in, dimensions of each cell are looked up during the area calculation...

in either case it would be it's own algorithm. 

This also could be expressed as an integral through the expression evaluator - a feature that is in the works from Michael's storm size integrator.

**Comment by taobrienlbl** [comment]
I see at least two reasons to consider separating this out from the area-of-connected-component calculation: (1) the grid cell areas would be useful for other algorithms (like a size integrator or any other integral involving dA), and (2) certain types of grids (e.g., irregular grids with complicated geometries) would provide this as part of the grid description file.  So generalizing at this point would mean that we wouldn't need to refactor code later if/when we start developing to support irregular grids.

**Comment by burlen** [comment]
you make some good points.

**Comment by burlen** [comment]
in the connected components area algorithm, I used the existing mechanism to get cell geometry and calculate cell area. it made sense there because we could do the calculations on two 1d arrays one w length nx and one with length ny, instead of a 2d array with dimensions nx*ny. this reduced the memory consumption and number of operations in that case.

however, we still may want/need this approach for the integrator and unstructured geometries. tbd.

It would be helpful to have an unstructured mesh to motivate/inform design and development.

**Comment by taobrienlbl** [comment]
Let's discuss the unstructured option next time we meet.  We a number of unstructured geometries to test on for sure.

**Comment by burlen** [comment]
this one is finished
