### ISSUE TITLE
cfreader cache location - default to PWD + command line option

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#237]
Currently, `teca_cf_reader` writes a cache file in the directory of the files that it scans.  This makes it difficult to use TECA on shared datasets, where the data directory may not have write permissions.  A workaround would be to create symlinks of the files in a user-writeable directory, but this doesn't seem like a clean solution.

We could instead assume/assert that the directory from which TECA is run is user-writeable, and we could provide an argument to `teca_cf_reader` (and a corresponding command line arg for TECA apps) that allows the user to specify the cache directory.  The latter option might be important for workflows that originate from a low-performance filesystem like $HOME.

For the first option, one way to unambiguously cache files would be to create a local directory called `.teca_cache/` and then create subdirectories therein that mimic the filesystem paths.

For example, if cfreader regex is something like  `/project/projectdirs/m1517/cascade/external_datasets/read_only_directory/*.nc`, then we would create a subdirectory like `$PWD/project/projectdirs/m1517/cascade/external_datasets/read_only_directory/` and insert the cache file there.

Thinking about this also raised a question related to #185 - if we provide files that exist across multiple directories, where does the cache file currently go?  I would guess it goes into the first directory in the list, but I'm not sure.  Does that affect how we would handle this alternate caching strategy?  @burlen, @elbashandy ?

**Comment by burlen** [comment]
The reader has some fall-backs and should always succeed in writing the cache file. Here's how it is implemented:  first it tries the same directory as the dataset, if that fails it tries the current working directory, if that fails it tries `$HOME`/ The latter should always succeed. 

In terms of performance, it shouldn't matter too much which file system the cache goes on because it is a small file, written by a single process.

What if we change the file selection algorithm to as follows:
first tries to write to `$TECA_METADATA_CACHE_PATH`, if that fails directory containing the files, if that fails current working dir, if that fails `$HOME`? That would at least give you control over where stuff gets put?


14b1563 adds `.md` extension to the cache files to make them easier to clean out.

**Comment by taobrienlbl** [comment]
Got it--I shouldn't have assumed there wouldn't be fallbacks.

I like the idea of attempting to use an environment variable for controlling where the cache files go.

**Comment by taobrienlbl** [comment]
I'm going to remove this issue from the Bayesian AR milestone, since the fallbacks you mentioned should allow this to work on datasets in read-only locations.  I'll leave the issue open as something to consider for a future version.

**Comment by burlen** [comment]
OK. I wasn't sure if you had experienced a failure in the current implementation. I know that things were working as of a few release ago because I did not have writer permissions in the directory that Michael had put his datasets.

also, I don't mean to be argumentative on this, adding a member variable to the reader is a fine addition. I mainly wanted to share that I had not done so because I had wanted this to be transparent to the user.

wrt #185 I hadn't considered that datasets containing multiple files would be spread across multiple directories. we should discuss the requirements for that use case more.

**Comment by taobrienlbl** [comment]
No, this was a thought that was partly based on a previous use of TECA on Michael's data, where I didn't have write access to his directory.  I hadn't realized this was fixed in more recent versions.

I'm good with the environment variable approach, member variable approach, or both: it's good to discuss the options, which was my original intent for opening this issue.

Regarding #185, a good example of a use case is the ERA5 dataset, which is on NERSC.  The glob pattern would be `/global/cscratch1/sd/taobrien/ERA5/e5.oper.an.vinteg/*/e5.oper.an.vinteg.162_07[12]_viwv[en].regn320sc*.nc`

**Comment by taobrienlbl** [comment]
btw, ERA5 is also one of the weird use cases where IVT would need to be calculated from its vector components, which are in different files.  ERA 20CR is the other one that I know of that would also require this: I have a python-based AR detector pipeline that deals with this as an example, if that helps.

**Comment by burlen** [comment]
> I hadn't realized this was fixed in more recent versions.

It was implemented that way from the beginning, so if you had an issue it likely still an issue

> /global/cscratch1/sd/taobrien/ERA5/e5.oper.an.vinteg/*/e5.oper.an.vinteg.162_07[12]_viwv[en].regn320sc*.nc

Assumptions I made when writing the reader:

1. all files in the dataset are in the same directory.
2. each file contains all the variables.

The most helpful thing we could have is documentation for all the various layouts we need to support.

**Comment by taobrienlbl** [comment]
Hmm...does a test exist for this fallback procedure? Perhaps we should add one if not.

Let me give some thought to your request for documenting the various data layouts.  I'll try to think of some effective ways to convey this information.

**Comment by burlen** [comment]
I recently added an algorithm property to the reader so that the metadata cache dir can be specified on the command line. @taobrienlbl is that sufficient to close this issue?

**Comment by taobrienlbl** [comment]
I noticed that earlier and was going to bring that up: yes, I think is sufficient.  Thanks
