### ISSUE TITLE
TECA_data-download--failed

### ISSUE THREAD

**Issue by bedassa** [LBL-EESA/TECA#405]
This what appears on the screen 
CMake Error at TECA_data-stamp/TECA_data-download.cmake:16 (message):
  Command failed: 1

   '/usr/bin/svn' 'co' 'svn://missmarple.lbl.gov/work3/teca/TECA_data' '-r49' '--non-interactive' 'TECA_data'

In the log file, I received the following 

svn: E000111: Unable to connect to a repository at URL 'svn://missmarple.lbl.gov/work3/teca/TECA_data'
svn: E000111: Can't connect to host 'missmarple.lbl.gov': Connection refused

**Comment by burlen** [comment]
This relates to the TECA_superbuild. 

## The quick fix
Perhaps the easiest work around for now, is to disable this step. In your build directory, edit the `CMakeCache.txt` file. Use a text editor, eg. `vim`. Find and set `ENABLE_TECA_TEST=OFF` and  `ENABLE_TECA_DATA=OFF`. Then `make -j` and `make -j install`. Should get you past this issue.

## The real fix
The NERSC power outage caused missmarple to reboot.  It didn't fully reboot. I will need to go on site to fix this as sshd did not start. Because of the lab's COVID 19 site access policies it may take a some time to get approved.

Note, we have recently decided to move our binary files to source forge this will be less of an issue when that is finalized (in next release). This change is a month or more out yet.

**Comment by bedassa** [comment]
Many thanks. The quick fix resolve it for me.
